name: nike_project
description: "Nike Project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  firebase_auth: ^4.19.4
  firebase_database: ^10.5.4
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  flutter_bloc: ^8.1.5
  provider: ^6.1.2
  easy_localization: ^3.0.6
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.0



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/lottie_type/
    - assets/images/other_type/
    - assets/images/svg_type/
    - assets/translations/


  # example:
  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/yekan_regular.ttf
        - asset: assets/fonts/yekan_bold.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
