import 'package:flutter/material.dart';

const Color kPrimaryColor = Color(0xff262a35);
const Color kSecondaryColor = Color(0xff217cf3);
const Color kPrimaryTextColor = Color(0xff262a35);
const Color kCaptionsTextColor = Color(0xffb3b6be);
const Color kBlackColor = Colors.black;
const Color kWhiteColor = Colors.white;
const Color kRedColor = Colors.red;
const Color kBlueColor = Colors.blue;
const Color kTransparentColor = Colors.transparent;
const Color kGreyColor = Colors.grey;
Color kGreyColorShade100 = Colors.grey.shade100;
Color kGreyColorShade200 = Colors.grey.shade200;
Color kGreyColorShade300 = Colors.grey.shade300;
Color kGreyColorShade400 = Colors.grey.shade400;
Color kGreyColorShade500 = Colors.grey.shade500;
Color kGreyColorShade600 = Colors.grey.shade600;
Color kGreyColorShade700 = Colors.grey.shade700;
Color kGreyColorShade800 = Colors.grey.shade800;
Color kGreyColorShade900 = Colors.grey.shade900;
